### ISSUE TITLE
 Error regarding login-button scss not found.

### ISSUE THREAD

**Issue by zaverichintan** [Urigo/angular2-meteor-accounts-ui#31]
>    While processing files with angular2-compilers (for target web.browser):
>    /client/main.scss: Scss compiler error: File to import: {}/node_modules/angular2-meteor-accounts-ui/build/login-buttons.scss not found in file: /home/zaverichintan/socially/{}/client/main.scss

Kindly resolve the issue.

**Comment by kamilkisiela** [comment]
Try to update `angular2-compilers` to `0.6.6`. I did it in Socially 2.0 and it works

**Comment by kamilkisiela** [comment]
Oh and try to update `angular2-meteor-accounts-ui` to the latest and to remove `@import '{}/node_modules/angular2-meteor-accounts-ui/build/login-buttons.scss'` from your `client/main.scss` because the package no longer have this file ([it uses `styles`](https://github.com/Urigo/angular2-meteor-accounts-ui/blob/master/src/login-buttons.ts#L16)).

**Comment by zaverichintan** [comment]
It gives error like this -

> zaverichintan@zaverichintan-X556UR:~/socially$ meteor
> [[[[[ ~/socially ]]]]]                        
> 
> => Started proxy.  
> => Started MongoDB.  
> W20161117-18:00:45.462(5.5)? (STDERR) /home/zaverichintan/socially/.meteor/local/build/programs/server/boot.js:348
> W20161117-18:00:45.497(5.5)? (STDERR) }).run();
> W20161117-18:00:45.497(5.5)? (STDERR)    ^
> W20161117-18:00:45.497(5.5)? (STDERR) 
> W20161117-18:00:45.498(5.5)? (STDERR) Error: Cannot find module '../core-js/symbol/iterator'
> W20161117-18:00:45.498(5.5)? (STDERR)     at require (packages/modules-runtime.js:109:19)
> W20161117-18:00:45.498(5.5)? (STDERR)     at meteorInstall.node_modules.babel-runtime.helpers.typeof.js (packages/modules.js:1092:17)
> W20161117-18:00:45.499(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
> W20161117-18:00:45.499(5.5)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
> W20161117-18:00:45.499(5.5)? (STDERR)     at Module.Mp.import (/home/zaverichintan/.meteor/packages/modules/.0.7.7.1v0rt8j++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
> W20161117-18:00:45.499(5.5)? (STDERR)     at meteorInstall.node_modules.meteor.webapp.webapp_server.js (/home/zaverichintan/socially/.meteor/local/build/programs/server/packages/webapp.js:33:26)
> W20161117-18:00:45.499(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
> W20161117-18:00:45.500(5.5)? (STDERR)     at require (packages/modules-runtime.js:106:16)
> W20161117-18:00:45.500(5.5)? (STDERR)     at /home/zaverichintan/socially/.meteor/local/build/programs/server/packages/webapp.js:842:1
> W20161117-18:00:45.500(5.5)? (STDERR)     at /home/zaverichintan/socially/.meteor/local/build/programs/server/packages/webapp.js:855:3

**Comment by kamilkisiela** [comment]
Are you sure it's `angular2-meteor-accounts-ui` fault? 

```
Cannot find module '../core-js/symbol/iterator'
```

It seems like you're missing `core-js/symbol/iterator`
